### ISSUE TITLE
Actualizar URL

### ISSUE THREAD

**Issue by jd-apprentice** [josu-dev/onemorechance#39]
![image](https://github.com/user-attachments/assets/77760a84-bdfe-42bc-9c61-2be6043e35a8)

Ya que el dominio se va a vencer y se decidio no renotar, hay que actualizar las URL.

@josu-dev si queres podemos poner el juego en mi dominio jonathan.com.ar u dejarlo con las url de github/vercel/etc

**Comment by josu-dev** [comment]
no me parece mal si lo queres dejar en tu dominio, algo de publicidad nula gratis si te parece bien

**Comment by jd-apprentice** [comment]
Dales! Lo dejamos entonces bajo jonathan.com.ar, tocará ver donde había quedado hosteado eventitos jeje

**Comment by josu-dev** [comment]
Genial. Main lo tenias hosteado en tu render, si queres lo pasamos al mio y damos de baja develop

**Comment by jd-apprentice** [comment]
Okis

**Comment by jd-apprentice** [comment]
![image](https://github.com/user-attachments/assets/dd895d38-942d-4f8e-9840-4af66303537f)

Efectivamente

**Comment by josu-dev** [comment]
Ya quedo main en mi render y sin deploy de develop hasta nuevo aviso.
